### ISSUE TITLE
效果如何呢

### ISSUE THREAD

**Issue by famousluuk** [jie3040/ACGAN-FG#2]
请问，在训练多少轮后以及最终的分类效果如何呢

**Comment by jie3040** [comment]
你好，感谢你的提问。以unseen fault class为 1，6，14的情况下。大概500-600 epoch 左右，精度可以到85左右。我们后续会更新具体的超参数.

**Comment by famousluuk** [comment]
> 好，谢谢你的提问。以看不见的故障等级为1，6，14的情况下。大概500-600 epoch左右，精度可以到85左右。我们后续会更新具体的超参数。

**Comment by famousluuk** [comment]
好的，我在不改变任何东西的情况下直接运行代码的，发现分类效果总是在33%左右，是不是因为超参数的问题
